// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrW3xW8Pu1SrztjTXfZSmWt9pkD_XMZHY',
    appId: '1:868528891047:web:174d9cb027c7ff7c2d2782',
    messagingSenderId: '868528891047',
    projectId: 'illumihome-79f32',
    authDomain: 'illumihome-79f32.firebaseapp.com',
    storageBucket: 'illumihome-79f32.appspot.com',
    measurementId: 'G-83EP6HDRVV',
    databaseURL: 'https://illumihome-79f32-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtdtw8fLH1GQkC5A7ROFc_J--AU7Xa03M',
    appId: '1:868528891047:android:6e4bf2213778e9a42d2782',
    messagingSenderId: '868528891047',
    projectId: 'illumihome-79f32',
    storageBucket: 'illumihome-79f32.appspot.com',
    databaseURL: 'https://illumihome-79f32-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARGxsheIOD7K4AP2FHPGiXeZhpq-v6SiA',
    appId: '1:868528891047:ios:67a5df70f08accd42d2782',
    messagingSenderId: '868528891047',
    projectId: 'illumihome-79f32',
    storageBucket: 'illumihome-79f32.appspot.com',
    iosBundleId: 'com.example.illumiHome',
    databaseURL: 'https://illumihome-79f32-default-rtdb.firebaseio.com',
  );
}